name: Build
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 1 * *'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Packages
        shell: bash
        run: |
          sudo apt-get install -y build-essential git cmake libspdlog-dev curl libsdl2-image-dev libsdl2-ttf-dev
          cmake -DCMAKE_BUILD_TYPE=MinSizeRel -G "CodeBlocks - Unix Makefiles" .
          cmake --build . --target zxpaint -- -j 2
