name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '41 7 * * 5'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  BITRAY_KEY: ${{ secrets.BINTRAY_API_KEY }} 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Build
      shell: bash
      run: |
        export CONAN_SYSREQUIRES_MODE=enabled
        sudo apt-get update
        sudo apt-get install -y build-essential git cmake curl pip libsdl2-image-dev libsdl2-ttf-dev
        pip install conan
        cmake -DCMAKE_BUILD_TYPE=MinSizeRel -G "CodeBlocks - Unix Makefiles" .
        cmake --build . --target zxpaint -- -j 2
